vijos/vj4

- vj4/handler/problem.py
- vj4/model/adaptor/problem.py
- vj4/ui/templates/components/problem_default.md
- vj4/ui/templates/problem_edit.html
- vj4/ui/templates/problem_main.html
> {create, edit} problem

- vj4/service/mailer.py
> fix typo in mailer.py

- vj4/model/document.py
- vj4/model/domain.py
- vj4/model/fs.py
- vj4/model/message.py
- vj4/model/opcount.py
- vj4/model/record.py
- vj4/model/system.py
- vj4/model/token.py
- vj4/model/user.py
Compatible with the latest version of PyMongo
> Issue #111

- requirements.txt
- vj4/app.py
- vj4/handler/base.py
- vj4/handler/domain.py
- vj4/handler/fs.py
- vj4/handler/problem.py
> remove usages of app.loop since it's deprecated in aiohttp 2.0

- vj4/ui/templates/partials/problem_list.html
- vj4/ui/templates/partials/problem_sidebar_normal.html
- vj4/ui/templates/problem_settings.html
- vj4/ui/templates/training_detail.html
what does these default-ors do? killing otherwise.
> Kill default-ors

- .pullapprove.yml
Every change needs at least one reviewer.
> Enforce pullapprove rules

- README.md
Project in Versioneye has been rebuilt so that ID is changed.
> Fix versioneye link in README

- vj4/ui/pages/record_main.page.styl
- vj4/ui/templates/record_main.html
- Hide statistics section. It will be moved to record_statistics page in the future.
- Adjust column width. Fix https://github.com/vijos/vj4/issues/247
- Adjust filter section.
Demo:
@twd2 @iceb0y PTAL
> Small improves for record_main page

- vj4/ui/components/time/time.page.js
- vj4/ui/pages/record_main.page.js
Fix https://github.com/vijos/vj4/issues/273
> Show relative time for dynamic added records

- vj4/locale/zh_CN.yaml
- vj4/ui/components/contest/contest_sidebar.page.styl
- vj4/ui/templates/partials/contest_sidebar.html
- vj4/ui/templates/partials/problem_sidebar_contest.html
- vj4/ui/templates/problem_detail.html
> Improve contest

- vj4/job/fs.py
- vj4/job/num.py
because the mongodb engine was changed to aiomongo.
> Hotfix: aggregate

- vj4/db.py
- vj4/test/base.py
To https://github.com/vijos/vj4/pull/331
> Fix Database Connection Leaks in Unit Tests

- vj4/error.py
- vj4/handler/contest.py
- vj4/handler/problem.py
- vj4/handler/record.py
- vj4/locale/zh_CN.yaml
- vj4/locale/zh_TW.yaml
- vj4/model/adaptor/contest.py
- vj4/model/builtin.py
- vj4/test/test_contest.py
- vj4/ui/templates/contest_detail.html
- vj4/ui/templates/contest_edit.html
- vj4/ui/templates/contest_scoreboard.html
- vj4/ui/templates/partials/contest_sidebar.html
- vj4/ui/templates/partials/problem_sidebar_contest.html
Also fixed the bug that users cannot see hidden submissions in contest_problem_submit even if he has the VIEW_HIDDEN_XXX permission.
> Separate show_func into show_record_func, show_scoreboard_func

- vj4/handler/base.py
- vj4/handler/contest.py
- vj4/handler/fs.py
> Fix dataset filename

- vj4/model/adaptor/contest.py
- vj4/test/test_contest.py
- vj4/ui/constant/contest.js
Extracted from https://github.com/vijos/vj4/pull/331
@twd2
> Add Assignment Rule

- vj4/handler/contest.py
- vj4/ui/templates/contest_edit.html
Extracted from https://github.com/vijos/vj4/pull/331
> Extract common methods from contest handler

- pylintrc
To https://github.com/vijos/vj4/pull/331
> Added pylintrc according to Project Styles

- README.md
* Fix inconsistency with python side
> Correct default ip header in README

- vj4/handler/base.py
- vj4/handler/contest.py
- vj4/handler/home.py
- vj4/handler/judge.py
- vj4/handler/misc.py
- vj4/handler/problem.py
- vj4/handler/user.py
- vj4/model/builtin.py
- vj4/model/opcount.py
> Rate limit grumbles

- vj4/server.py
3 new arguments:
1. `--listen-owner=www-data`
2. `--listen-group=www-data`
3. `--listen-mode=660`
> Set unix socket file permission

- vj4/server.py
Reverts vijos/vj4#429, and make user/group and file mode default when arguments are not passed.
> Revert "Revert "Set unix socket file permission""

- README.md
- requirements.txt
- vj4/app.py
- vj4/handler/base.py
- vj4/handler/fs.py
> Fix interface change with aiohttp3

- vj4/handler/homework.py
- vj4/handler/judge.py
- vj4/handler/record.py
- vj4/model/adaptor/contest.py
- vj4/model/record.py
- vj4/test/test_contest.py
Related to `feature/homework` (#460)
https://github.com/vijos/vj4/pull/460#discussion_r259571773
> Add `doc_type` field in `record` model

- vj4/handler/problem.py
- vj4/locale/zh_CN.yaml
- vj4/model/domain.py
- vj4/ui/templates/problem_edit.html
Show a checkbox "assign numeric ID" when creating problems, default value is True.
Close #330
> Assigning numeric ID for problems

- vj4/model/domain.py
- vj4/model/system.py
> problem counter for system domain

- vj4/error.py
- vj4/handler/base.py
- vj4/handler/discussion.py
- vj4/handler/record.py
- vj4/locale/zh_CN.yaml
- vj4/model/adaptor/contest.py
> fix multi arg

- vj4/handler/domain.py
- vj4/model/domain.py
* clear `gravatar` field
* use `startswith`
* search builtin domains case-insensitively
> Fix domain selector

- vj4/ui/templates/domain_main.html
> adding NOJ as an Online Judge

- vj4/locale/ko.yaml
Added Korean support. (maybe someone would use this in the future....😃)
> Created ko.yaml

- .github/workflows/test.yml
- README.md
- requirements.txt
- vj4/template.py
- vj4/util/misc.py
It's a no-op since 2.9 and removed since 3.1 .
https://jinja.palletsprojects.com/en/3.0.x/extensions/#with-statement
> Changes to work with latest environment and libraries
